# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "CLI project template for Go"
  homepage "https://github.com/skmatz/go-cmd-template"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/skmatz/go-cli-template/releases/download/v0.1.2/hello_0.1.2_darwin_x86_64.tar.gz"
    sha256 "4948e4c80275352ffe84a6f1229b3bb26f9ddeb2d0d8eccb5b87426284b5eb14"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/skmatz/go-cli-template/releases/download/v0.1.2/hello_0.1.2_linux_x86_64.tar.gz"
    sha256 "f4e78c57f289d2ee07b6efe9c5a04b32b7e8348b2fc3258cd87b90077047d4ae"
  end

  def install
    bin.install "hello"
  end

  test do
    system "#{bin}/hello version"
  end
end
